package com.masai.enm;

public enum Feedback {

	YET_TO_BE_CLOSED , 
	GREAT_EXP , 
	GOOD_EXP , 
	BAD_EXP , 
	HORRIBLE_EXP , 
	HAPPY_ADDRESSING_YOUR_ISSUE , 
	ISSUE_IS_ADDRESSED_NOW , 
	ISSUE_NOT_MEANT_TO_BE_ADDRESSED , 
	WRONG_CATEGORY_CHOOSEN , 
	WAS_HORRIBLE_ADDRESSING_ISSUE , 
	DO_NOT_RAISE_ISSUE_EVER_AGAIN_PLEASE;
	
}
